name: Update README Activity

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch: # Te permite ejecutarlo manualmente desde la pestaña Actions de GitHub

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Profile README

    steps:
      # 1. Clonar tu repositorio para poder editar el README
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      # 2. Buscar tu actividad de GitHub e inyectarla en el README
      - name: Update Recent Activity
        uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
