name: Generate pacman animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # 1. Clonar el repositorio completo 
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Generar la animación de Pacman
      - name: generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      # 3. Crear la carpeta 'dist' y mover TODOS los SVG que generó la acción
      - name: Prepare artifact directory
        run: |
          mkdir -p dist
          mv pacman-contribution-graph*.svg dist/

      # 4. Subir el contenido de 'dist' a la rama output
      - name: push pacman-contribution-graph.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
